resources:

- name: app-src
  type: git
  source:
    uri: https://github.com/markstgodard/phpapp.git
    branch: master

- name: ci-scripts
  type: git
  source:
    uri: https://github.com/markstgodard/ci-simple.git

jobs:

- name: unit-tests
  plan:
  - aggregate:
    - get: ci-scripts
    - get: app-src
      trigger: true
  - task: run-unit
    file: ci-scripts/tasks/unit-tests.yml

- name: lint
  plan:
  - aggregate:
    - get: ci-scripts
    - get: app-src
      trigger: true
  - task: run-unit
    file: ci-scripts/tasks/lint.yml

- name: deploy
  plan:
  - aggregate:
    - get: ci-scripts
    - get: app-src
      passed: [lint, unit-tests]
      trigger: true
  - task: deploy
    file: ci-scripts/tasks/deploy.yml

