apiVersion: v1
kind: Pod
metadata:
  name: phpapp
spec:
  containers:
    - name: main
      image: markstgodard/phpapp:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.1"
